FROM node:20-bullseye

WORKDIR /app

ENV PORT=3000

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm ci --legacy-peer-deps

# Copy source code
COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"] 