# Cloud Build pipeline  (v1 format)
substitutions:
  _REGION: us-central1    # change if you move regions

options:
  logging: CLOUD_LOGGING_ONLY

steps:
###############################################################################
# 1  Build & push backend container
###############################################################################
- id: backend-build
  name: gcr.io/cloud-builders/docker
  dir: backend
  args: [
    'build','-t',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/backend-repo/backend:$SHORT_SHA',
    '.'
  ]

- id: backend-push
  name: gcr.io/cloud-builders/docker
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/backend-repo/backend:$SHORT_SHA'
  ]

###############################################################################
# 2  Build & push frontend container
###############################################################################
- id: frontend-build
  name: gcr.io/cloud-builders/docker
  dir: frontend
  args: [
    'build','-t',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/frontend-repo/frontend:$SHORT_SHA',
    '.'
  ]

- id: frontend-push
  name: gcr.io/cloud-builders/docker
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/frontend-repo/frontend:$SHORT_SHA'
  ]

###############################################################################
# 3  Terraform apply (infra changes)
###############################################################################
- id: terraform-apply
  name: hashicorp/terraform:light          # alpine image with terraform only
  dir: infra
  entrypoint: /bin/sh                      # <— key fix: run shell, not terraform
  env:
    - GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=terraform-sa@$PROJECT_ID.iam.gserviceaccount.com
  args:
    - -c
    - |
      terraform init \
        -backend-config="bucket=tfstate-${PROJECT_ID}" \
        -backend-config="prefix=live"

      # Check if resources already exist and import them
      if terraform state list google_firestore_database.default &>/dev/null; then
        echo "Firestore DB already imported."
      else
        terraform import google_firestore_database.default "projects/${PROJECT_ID}/databases/(default)" || true
      fi

      if terraform state list google_cloud_tasks_queue.notifications &>/dev/null; then
        echo "Cloud Tasks queue already imported."
      else
        terraform import google_cloud_tasks_queue.notifications "projects/${PROJECT_ID}/locations/${_REGION}/queues/notification-tasks" || true
      fi

      if terraform state list google_cloud_run_v2_service.backend &>/dev/null; then
        echo "Backend service already imported."
      else
        terraform import google_cloud_run_v2_service.backend "${_REGION}/backend-api" || true
      fi

      if terraform state list google_cloud_run_v2_service.frontend &>/dev/null; then
        echo "Frontend service already imported."
      else
        terraform import google_cloud_run_v2_service.frontend "${_REGION}/frontend-ssr" || true
      fi

      if terraform state list google_secret_manager_secret.sendgrid &>/dev/null; then
        echo "SendGrid secret already imported."
      else
        terraform import google_secret_manager_secret.sendgrid "projects/${PROJECT_ID}/secrets/SENDGRID_KEY" || true
      fi

      if terraform state list google_secret_manager_secret.twilio &>/dev/null; then
        echo "Twilio secret already imported."
      else
        terraform import google_secret_manager_secret.twilio "projects/${PROJECT_ID}/secrets/TWILIO_SID" || true
      fi

      # Apply changes with -refresh-only first to sync state, then apply actual changes
      terraform apply -refresh-only -auto-approve -input=false \
        -var="project_id=${PROJECT_ID}" \
        -var="region=${_REGION}" \
        -var="image_tag=${SHORT_SHA}" \
        -var="cloud_build_sa=${PROJECT_NUMBER}@cloudbuild.gserviceaccount.com" \
        -parallelism=10 \
        -timeout=2m

      echo "Starting actual Terraform apply with 5-minute timeout..."
      # Now apply the real changes with more verbose output
      TF_LOG=INFO terraform apply -auto-approve -input=false \
        -var="project_id=${PROJECT_ID}" \
        -var="region=${_REGION}" \
        -var="image_tag=${SHORT_SHA}" \
        -var="cloud_build_sa=${PROJECT_NUMBER}@cloudbuild.gserviceaccount.com" \
        -parallelism=10 \
        -timeout=5m

###############################################################################
# (optional) Slack / webhook notifier
###############################################################################
# - id: notify
#   name: curlimages/curl
#   entrypoint: curl
#   args: ['-X','POST','https://hooks.slack.com/services/…']

images:
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/backend-repo/backend:$SHORT_SHA'
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/frontend-repo/frontend:$SHORT_SHA'

timeout: 1800s   # 30 minutes
