# Simplified Cloud Build pipeline for development (frontend only)
substitutions:
  _REGION: us-central1    # change if you move regions

options:
  logging: CLOUD_LOGGING_ONLY

steps:
###############################################################################
# 1  Build & push frontend container only
###############################################################################

# Add a step to fetch Firebase config from Secret Manager
- id: fetch-firebase-config
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      echo "Fetching Firebase config from Secret Manager..."
      gcloud secrets versions access latest --secret=firebase-web-config --project=$PROJECT_ID > frontend/.env.local
      echo "Firebase config fetched successfully"

- id: frontend-build
  name: gcr.io/cloud-builders/docker
  dir: frontend
  args: [
    'build','-t',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/frontend-repo/frontend:dev',
    '.'
  ]

- id: frontend-push
  name: gcr.io/cloud-builders/docker
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/frontend-repo/frontend:dev'
  ]

###############################################################################
# 2  Deploy only the frontend service
###############################################################################
- id: deploy-frontend
  name: gcr.io/cloud-builders/gcloud
  args:
    - 'run'
    - 'deploy'
    - 'frontend-dev'
    - '--image'
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/frontend-repo/frontend:dev'
    - '--region'
    - '${_REGION}'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'NEXT_PUBLIC_API_BASE=https://backend-api-${_REGION}.a.run.app'

images:
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/frontend-repo/frontend:dev'

timeout: 600s   # 10 minutes 