# Cloud Build pipeline  (v1 format)
substitutions:
  _REGION: us-central1    # change if you move regions

options:
  logging: CLOUD_LOGGING_ONLY

steps:
###############################################################################
# 1  Build & push backend container
###############################################################################
- id: backend-build
  name: gcr.io/cloud-builders/docker
  dir: backend
  args: [
    'build','-t',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/backend-repo/backend:$SHORT_SHA',
    '.'
  ]

- id: backend-push
  name: gcr.io/cloud-builders/docker
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/backend-repo/backend:$SHORT_SHA'
  ]

###############################################################################
# 2  Build & push frontend container
###############################################################################

# Add a step to fetch Firebase config from Secret Manager
- id: fetch-firebase-config
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      echo "Fetching Firebase config from Secret Manager..."
      gcloud secrets versions access latest --secret=firebase-web-config --project=$PROJECT_ID > frontend/.env.local
      echo "Firebase config fetched successfully"

- id: frontend-build
  name: gcr.io/cloud-builders/docker
  dir: frontend
  args: [
    'build','-t',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/frontend-repo/frontend:$SHORT_SHA',
    '.'
  ]

- id: frontend-push
  name: gcr.io/cloud-builders/docker
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/frontend-repo/frontend:$SHORT_SHA'
  ]

###############################################################################
# 3  Build & push worker container
###############################################################################
- id: worker-build
  name: gcr.io/cloud-builders/docker
  dir: backend/worker
  args: [
    'build','-t',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/backend-repo/worker:$SHORT_SHA',
    '.'
  ]

- id: worker-push
  name: gcr.io/cloud-builders/docker
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/$PROJECT_ID/backend-repo/worker:$SHORT_SHA'
  ]

###############################################################################
# 4  Terraform apply (infra changes)
###############################################################################
- id: terraform-apply
  name: hashicorp/terraform:light          # alpine image with terraform only
  dir: infra
  entrypoint: /bin/sh                      # <— key fix: run shell, not terraform
  env:
    - GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=terraform-sa@$PROJECT_ID.iam.gserviceaccount.com
  args:
    - -c
    - |
      # Initialize terraform
      terraform init \
        -backend-config="bucket=tfstate-${PROJECT_ID}" \
        -backend-config="prefix=live"

      # List current state for debugging
      echo "Current Terraform state:"
      terraform state list || true
      
      # Import Firestore database if not already in state
      if terraform state list google_firestore_database.default &>/dev/null; then
        echo "Firestore DB already imported."
      else
        terraform import google_firestore_database.default "projects/${PROJECT_ID}/databases/(default)" || true
      fi

      if terraform state list google_cloud_tasks_queue.notifications &>/dev/null; then
        echo "Cloud Tasks queue already imported."
      else
        terraform import google_cloud_tasks_queue.notifications "projects/${PROJECT_ID}/locations/${_REGION}/queues/notification-tasks" || true
      fi

      if terraform state list google_cloud_run_v2_service.backend &>/dev/null; then
        echo "Backend service already imported."
      else
        terraform import google_cloud_run_v2_service.backend "${_REGION}/backend-api" || true
      fi

      if terraform state list google_cloud_run_v2_service.frontend &>/dev/null; then
        echo "Frontend service already imported."
      else
        terraform import google_cloud_run_v2_service.frontend "${_REGION}/frontend-ssr" || true
      fi

      if terraform state list google_cloud_run_v2_service.worker &>/dev/null; then
        echo "Worker service already imported."
      else
        terraform import google_cloud_run_v2_service.worker "${_REGION}/notification-worker" || true
      fi

      if terraform state list google_secret_manager_secret.sendgrid &>/dev/null; then
        echo "SendGrid secret already imported."
      else
        terraform import google_secret_manager_secret.sendgrid "projects/${PROJECT_ID}/secrets/SENDGRID_KEY" || true
      fi

      if terraform state list google_secret_manager_secret.twilio &>/dev/null; then
        echo "Twilio secret already imported."
      else
        terraform import google_secret_manager_secret.twilio "projects/${PROJECT_ID}/secrets/TWILIO_SID" || true
      fi

      if terraform state list google_secret_manager_secret.firebase_web_config &>/dev/null; then
        echo "Firebase web config secret already imported."
      else
        terraform import google_secret_manager_secret.firebase_web_config "projects/${PROJECT_ID}/secrets/firebase-web-config" || true
      fi

      # Import module resources to avoid conflicts
      if terraform state list module.backend_service.google_cloud_run_service.this &>/dev/null; then
        echo "Module backend service already imported."
      else
        echo "Not importing module.backend_service as it's been commented out to avoid conflicts."
        # terraform import module.backend_service.google_cloud_run_service.this "${_REGION}/backend-api" || true
      fi

      # Remove any secret versions from state first to avoid conflicts
      if terraform state list | grep -q "module.secrets.google_secret_manager_secret_version"; then
        echo "Removing secret versions from state to avoid conflicts..."
        terraform state rm 'module.secrets.google_secret_manager_secret_version.init["SENDGRID_KEY"]' || true
        terraform state rm 'module.secrets.google_secret_manager_secret_version.init["TWILIO_SID"]' || true
        terraform state rm 'module.secrets.google_secret_manager_secret_version.init["STRIPE_SK"]' || true
      fi

      # Use proper quoting for the state list commands
      if terraform state list 'module.secrets.google_secret_manager_secret.this["SENDGRID_KEY"]' &>/dev/null; then
        echo "Module SendGrid secret already imported."
      else
        terraform import 'module.secrets.google_secret_manager_secret.this["SENDGRID_KEY"]' "projects/${PROJECT_ID}/secrets/SENDGRID_KEY" || true
      fi

      if terraform state list 'module.secrets.google_secret_manager_secret.this["TWILIO_SID"]' &>/dev/null; then
        echo "Module Twilio secret already imported."
      else
        terraform import 'module.secrets.google_secret_manager_secret.this["TWILIO_SID"]' "projects/${PROJECT_ID}/secrets/TWILIO_SID" || true
      fi

      if terraform state list 'module.secrets.google_secret_manager_secret.this["STRIPE_SK"]' &>/dev/null; then
        echo "Module Stripe secret already imported."
      else
        terraform import 'module.secrets.google_secret_manager_secret.this["STRIPE_SK"]' "projects/${PROJECT_ID}/secrets/STRIPE_SK" || true
      fi

      if terraform state list 'module.secrets.google_secret_manager_secret.this["firebase-web-config"]' &>/dev/null; then
        echo "Module Firebase web config secret already imported."
      else
        terraform import 'module.secrets.google_secret_manager_secret.this["firebase-web-config"]' "projects/${PROJECT_ID}/secrets/firebase-web-config" || true
      fi

      # Import Google OAuth client secrets for Calendar integration
      if terraform state list 'module.secrets.google_secret_manager_secret.this["GOOGLE_CLIENT_ID"]' &>/dev/null; then
        echo "Module Google client ID secret already imported."
      else
        terraform import 'module.secrets.google_secret_manager_secret.this["GOOGLE_CLIENT_ID"]' "projects/${PROJECT_ID}/secrets/GOOGLE_CLIENT_ID" || true
      fi

      if terraform state list 'module.secrets.google_secret_manager_secret.this["GOOGLE_CLIENT_SECRET"]' &>/dev/null; then
        echo "Module Google client secret already imported."
      else
        terraform import 'module.secrets.google_secret_manager_secret.this["GOOGLE_CLIENT_SECRET"]' "projects/${PROJECT_ID}/secrets/GOOGLE_CLIENT_SECRET" || true
      fi

      if terraform state list google_secret_manager_secret.calendar_sa_key &>/dev/null; then
        echo "Calendar SA secret already imported."
      else
        terraform import google_secret_manager_secret.calendar_sa_key "projects/${PROJECT_ID}/secrets/calendar-sync-sa" || true
      fi

      # Before normal apply, remove any stale resources that were commented out
      echo "Checking for stale resources to remove from state..."
      
      # Check if module.backend_service is in the state
      if terraform state list | grep -q "module.backend_service"; then
        # Check if it's uncommented in the code
        if ! grep -q "^[^#/].*module \"backend_service\"" infra/main.tf; then
          echo "Removing commented out module.backend_service from state..."
          terraform state rm module.backend_service || true
        fi
      fi
      
      # Check if these direct resources are in state but commented in code
      if terraform state list | grep -q "google_secret_manager_secret.sendgrid"; then
        if grep -q "\/\*\|^#" infra/secrets.tf | grep -q "google_secret_manager_secret.*sendgrid"; then
          echo "Removing commented out google_secret_manager_secret.sendgrid from state..."
          terraform state rm google_secret_manager_secret.sendgrid || true
        fi
      fi
      
      if terraform state list | grep -q "google_secret_manager_secret.twilio"; then
        if grep -q "\/\*\|^#" infra/secrets.tf | grep -q "google_secret_manager_secret.*twilio"; then
          echo "Removing commented out google_secret_manager_secret.twilio from state..."
          terraform state rm google_secret_manager_secret.twilio || true
        fi
      fi

      # Apply changes with -refresh-only first to sync state, then apply actual changes
      terraform apply -refresh-only -auto-approve -input=false \
        -var="project_id=${PROJECT_ID}" \
        -var="region=${_REGION}" \
        -var="image_tag=${SHORT_SHA}" \
        -var="cloud_build_sa=${PROJECT_NUMBER}@cloudbuild.gserviceaccount.com" \
        -parallelism=10

      echo "Starting actual Terraform apply..."
      # Now apply the real changes with more verbose output
      TF_LOG=INFO terraform apply -auto-approve -input=false \
        -var="project_id=${PROJECT_ID}" \
        -var="region=${_REGION}" \
        -var="image_tag=${SHORT_SHA}" \
        -var="cloud_build_sa=${PROJECT_NUMBER}@cloudbuild.gserviceaccount.com" \
        -parallelism=10

###############################################################################
# (optional) Slack / webhook notifier
###############################################################################
# - id: notify
#   name: curlimages/curl
#   entrypoint: curl
#   args: ['-X','POST','https://hooks.slack.com/services/…']

images:
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/backend-repo/backend:$SHORT_SHA'
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/frontend-repo/frontend:$SHORT_SHA'
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/backend-repo/worker:$SHORT_SHA'

timeout: 1800s   # 30 minutes
