version: '3.8'

services:
  backend:
    # Use cloud-built container instead of local build
    image: ${BACKEND_IMAGE:-us-central1-docker.pkg.dev/auto-mech-booking-0418/backend-repo/backend:latest}
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_CLOUD_PROJECT=auto-mech-booking
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - FIREBASE_AUTH_EMULATOR_HOST=firestore:9099
    depends_on:
      - firestore

  frontend:
    # Use cloud-built container instead of local build
    image: ${FRONTEND_IMAGE:-us-central1-docker.pkg.dev/auto-mech-booking-0418/frontend-repo/frontend:latest}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

  worker:
    # Add the notification worker
    image: ${WORKER_IMAGE:-us-central1-docker.pkg.dev/auto-mech-booking-0418/backend-repo/worker:latest}
    ports:
      - "8081:8080"
    environment:
      - GOOGLE_CLOUD_PROJECT=auto-mech-booking
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - SMTP2GO_USERNAME=${SMTP2GO_USERNAME}
      - SMTP2GO_PASSWORD=${SMTP2GO_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL:-noreply@monkeyboigarage.com}
      - BOOKING_URL=${BOOKING_URL:-http://localhost:3000/book}
    depends_on:
      - firestore

  firestore:
    image: google/cloud-sdk:latest
    ports:
      - "8080:8080"
      - "9099:9099"
      - "4000:4000"
    command: >
      bash -c "
        gcloud config set project auto-mech-booking &&
        firebase emulators:start --only firestore,auth,ui --host 0.0.0.0
      "
    volumes:
      - ./.firebase:/root/.config/firebase
      - ./firebase.json:/firebase.json
      - ./firestore.rules:/firestore.rules