services:
  backend:
    build: ./backend
    ports: [ "8080:8080" ]
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/adc.json
      GOOGLE_CLOUD_PROJECT: auto-mech-booking-0418
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/secrets/adc.json:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports: [ "3000:3000" ]
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
